### ISSUE TITLE
Amend the effect on end and nether as its impossible to sleep in these detentions 

### ISSUE THREAD

**Issue by Darkside247** [ReviversMC/bettersleeping#3]
is there a way to remove the effects in worlds its not possible to sleep in as its a little unfair to not be able to sleep and can be deadly in these detentions

**Comment by MinerB4** [comment]
It also kind of makes sense since Time in these dimensions are useless.

Light Levels never change nor does any behavior depend on Time in the other dimensions.

**Comment by NebelNidas** [comment]
Sorry for the *very* late reply, I've been busy IRL lately and completely forgot this issue was still a thing. @Darkside247's originally reported issue has been fixed now by 0d18a7c7481d19b271c343afd1bccf924ba0b70a!
@MinerB4 This would be a very easy fix, too, though I'm not sure if this should be the default behavior. Because yes, time doesn't visually advance, but you're still staying up for a very long time while theoretically being able to sleep, which *should* be punished going by BetterSleeping's initial idea? 🤔

**Comment by NebelNidas** [comment]
Please try out [0.6.0](https://github.com/ReviversMC/bettersleeping/releases/tag/0.6.0)!
